import React from 'react';
import '../layout.css';
import 'bootstrap/dist/css/bootstrap.css';
import ContactMailOutlinedIcon from '@mui/icons-material/ContactMailOutlined'; import '../App.css';

const Skill = () => {
  return (
   <>
    <div className='skilldiv' style={{ height: "70vh", width: "100%", backgroundColor: "#9e9b9b29" }}>
                <div style={{ height: "80px", width: "40px", backgroundColor: "transparent", marginLeft: "40vw" }}><ContactMailOutlinedIcon className='icon1' style={{ height: "150px", width: "75px", color: "#2857a4",marginTop:"50px" }} /></div>
                <div id='skills' style={{ fontSize: "50px", color: "#2857a4", marginTop: "10px", marginLeft: "70px" }}>SKILLS</div>
                <div className='mySkills1' style={{ height: "35px", width: "190px", backgroundColor: "silver", borderRadius: "20px", display: "flex", marginLeft: "230px", marginTop: "80px" }}><div style={{ height: "35px", width: "170px", backgroundColor: "#2857a4", borderTopLeftRadius: '20px', borderBottomLeftRadius: "20px" }}><h5 style={{ marginTop: "3px", marginLeft: "-100px", color: "white", fontSize: "20px", fontWeight: "normal" }}>HTML</h5></div></div>
                <div className='mySkills2'style={{ height: "35px", width: "190px", backgroundColor: "silver", borderRadius: "20px", display: "flex", marginLeft: "500px", marginTop: "-36px" }}><div style={{ height: "35px", width: "170px", backgroundColor: "#FF4500", borderTopLeftRadius: '20px', borderBottomLeftRadius: "20px" }}><h5 style={{ marginTop: "3px", marginLeft: "-100px", color: "white", fontSize: "20px", fontWeight: "normal" }}>CSS</h5></div></div>
                <div className='mySkills3' style={{ height: "35px", width: "190px", backgroundColor: "silver", borderRadius: "20px", display: "flex", marginLeft: "800px", marginTop: "-36px" }}><div style={{ height: "35px", width: "170px", backgroundColor: "#795F80", borderTopLeftRadius: '20px', borderBottomLeftRadius: "20px" }}><h5 style={{ marginTop: "3px", marginLeft: "-70px", color: "white", fontSize: "20px", fontWeight: "normal" }}>Bootstrap</h5></div></div>
                <div className='mySkills4' style={{ height: "35px", width: "190px", backgroundColor: "silver", borderRadius: "20px", display: "flex", marginLeft: "1100px", marginTop: "-36px" }}><div style={{ height: "35px", width: "170px", backgroundColor: "#2857a4", borderTopLeftRadius: '20px', borderBottomLeftRadius: "20px" }}><h5 style={{ marginTop: "3px", marginLeft: "-60px", color: "white", fontSize: "20px", fontWeight: "normal" }}>Javascript</h5></div></div>
                <div className='mySkills5'style={{ height: "35px", width: "190px", backgroundColor: "silver", borderRadius: "20px", display: "flex", marginLeft: "230px", marginTop: "80px" }}><div style={{ height: "35px", width: "170px", backgroundColor: "#7CB68E", borderTopLeftRadius: '20px', borderBottomLeftRadius: "20px" }}><h5 style={{ marginTop: "3px", marginLeft: "-100px", color: "white", fontSize: "20px", fontWeight: "normal" }}>DOM</h5></div></div>
                <div className='mySkills6' style={{ height: "35px", width: "190px", backgroundColor: "silver", borderRadius: "20px", display: "flex", marginLeft: "500px", marginTop: "-36px" }}><div style={{ height: "35px", width: "170px", backgroundColor: "#2857a4", borderTopLeftRadius: '20px', borderBottomLeftRadius: "20px" }}><h5 style={{ marginTop: "3px", marginLeft: "-100px", color: "white", fontSize: "20px", fontWeight: "normal" }}>React</h5></div></div>
                <div className='mySkills7' style={{ height: "35px", width: "190px", backgroundColor: "silver", borderRadius: "20px", display: "flex", marginLeft: "800px", marginTop: "-36px" }}><div style={{ height: "35px", width: "170px", backgroundColor: "#795F80", borderTopLeftRadius: '20px', borderBottomLeftRadius: "20px" }}><h5 style={{ marginTop: "3px", marginLeft: "-100px", color: "white", fontSize: "20px", fontWeight: "normal" }}>Redux</h5></div></div>
                <div className='mySkills8'style={{ height: "35px", width: "190px", backgroundColor: "silver", borderRadius: "20px", display: "flex", marginLeft: "1100px", marginTop: "-36px" }}><div style={{ height: "35px", width: "170px", backgroundColor: "#7CB68E", borderTopLeftRadius: '20px', borderBottomLeftRadius: "20px" }}><h5 style={{ marginTop: "3px", marginLeft: "-60px", color: "white", fontSize: "20px", fontWeight: "normal" }}>Restful API</h5></div></div>
                <div className='mySkills9'style={{ height: "35px", width: "190px", backgroundColor: "silver", borderRadius: "20px", display: "flex", marginLeft: "400px", marginTop: "80px" }}><div style={{ height: "35px", width: "170px", backgroundColor: "#795F80", borderTopLeftRadius: '20px', borderBottomLeftRadius: "20px" }}><h5 style={{ marginTop: "3px", marginLeft: "-80px", color: "white", fontSize: "20px", fontWeight: "normal" }}>Node Js</h5></div></div>
                <div className='mySkills10'style={{ height: "35px", width: "190px", backgroundColor: "silver", borderRadius: "20px", display: "flex", marginLeft: "900px", marginTop: "-36px" }}><div style={{ height: "35px", width: "170px", backgroundColor: "#FF4500", borderTopLeftRadius: '20px', borderBottomLeftRadius: "20px" }}><h5 style={{ marginTop: "3px", marginLeft: "-60px", color: "white", fontSize: "20px", fontWeight: "normal" }}>MongoDB</h5></div></div>
            </div>
   
   </>
  )
}

export default Skill